// AUTO-GENERATED by odds_fetcher.py — do not edit manually
// Fetched: 2026-08-27T18:58:57.300243+00:00
// Date:    2026-08-27

const ODDS_DATA = {
  "fetched_at": "2026-08-27T18:58:57.300243+00:00",
  "date": "2026-08-27",
  "games": [
    {
      "id": "484411acaf382c9b99aa08d6e6ccd79f",
      "home": "Washington Nationals",
      "away": "Colorado Rockies",
      "time": "5:06 PM ET",
      "commence": "2026-08-27T17:06:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Washington Nationals -700 / Colorado Rockies +550",
        "spread": "Washington Nationals -2.5 (-138)",
        "total": "O/U 8.5 (Over -136 / Under +102)",
        "raw": {
          "homeML": -700,
          "awayML": 550,
          "homeSpread": -2.5,
          "homeSpreadOdds": -138,
          "awaySpread": 2.5,
          "awaySpreadOdds": 104,
          "total": 8.5,
          "overOdds": -136,
          "underOdds": 102
        }
      },
      "props": {}
    },
    {
      "id": "f9efae328746bce7662ce368bb304f87",
      "home": "St. Louis Cardinals",
      "away": "Baltimore Orioles",
      "time": "6:16 PM ET",
      "commence": "2026-08-27T18:16:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "St. Louis Cardinals -460 / Baltimore Orioles +370",
        "spread": "St. Louis Cardinals -2.5 (-112)",
        "total": "O/U 7.5 (Over -132 / Under +100)",
        "raw": {
          "homeML": -460,
          "awayML": 370,
          "homeSpread": -2.5,
          "homeSpreadOdds": -112,
          "awaySpread": 2.5,
          "awaySpreadOdds": -118,
          "total": 7.5,
          "overOdds": -132,
          "underOdds": 100
        }
      },
      "props": {
        "Trevor Rogers": {
          "pitcher_earned_runs": {
            "point": 3.5,
            "over": -145,
            "under": 105,
            "overStr": "-145",
            "underStr": "+105"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": 125,
            "under": -165,
            "overStr": "+125",
            "underStr": "-165"
          },
          "pitcher_outs": {
            "point": 17.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_strikeouts": {
            "point": 6.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_walks": {
            "point": 0.5,
            "over": -120,
            "under": -115,
            "overStr": "-120",
            "underStr": "-115"
          }
        }
      }
    },
    {
      "id": "68a5f4cb0d65f2fc93321ae004027c46",
      "home": "New York Yankees",
      "away": "Houston Astros",
      "time": "11:06 PM ET",
      "commence": "2026-08-27T23:06:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "New York Yankees -150 / Houston Astros +140",
        "spread": "New York Yankees -1.5 (+128)",
        "total": "O/U 8.0 (Over -115 / Under -105)",
        "raw": {
          "homeML": -150,
          "awayML": 140,
          "homeSpread": -1.5,
          "homeSpreadOdds": 128,
          "awaySpread": 1.5,
          "awaySpreadOdds": -154,
          "total": 8.0,
          "overOdds": -115,
          "underOdds": -105
        }
      },
      "props": {
        "Hayden Wesneski": {
          "pitcher_outs": {
            "point": 15.5,
            "over": 120,
            "under": -165,
            "overStr": "+120",
            "underStr": "-165"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": 105,
            "under": -140,
            "overStr": "+105",
            "underStr": "-140"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -118,
            "under": -115,
            "overStr": "-118",
            "underStr": "-115"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -140,
            "under": 105,
            "overStr": "-140",
            "underStr": "+105"
          }
        },
        "Gerrit Cole": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": -140,
            "under": 110,
            "overStr": "-140",
            "underStr": "+110"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 125,
            "under": -175,
            "overStr": "+125",
            "underStr": "-175"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 136,
            "under": -182,
            "overStr": "+136",
            "underStr": "-182"
          }
        }
      }
    },
    {
      "id": "55ee0a20c48002519602e2362965c6e6",
      "home": "Toronto Blue Jays",
      "away": "Kansas City Royals",
      "time": "11:08 PM ET",
      "commence": "2026-08-27T23:08:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Toronto Blue Jays -102 / Kansas City Royals -106",
        "spread": "Toronto Blue Jays +1.5 (-172)",
        "total": "O/U 8.5 (Over -104 / Under -118)",
        "raw": {
          "homeML": -102,
          "awayML": -106,
          "homeSpread": 1.5,
          "homeSpreadOdds": -172,
          "awaySpread": -1.5,
          "awaySpreadOdds": 142,
          "total": 8.5,
          "overOdds": -104,
          "underOdds": -118
        }
      },
      "props": {
        "Noah Cameron": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -145,
            "under": 105,
            "overStr": "-145",
            "underStr": "+105"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": 110,
            "under": -150,
            "overStr": "+110",
            "underStr": "-150"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -115,
            "under": -118,
            "overStr": "-115",
            "underStr": "-118"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -197,
            "under": 147,
            "overStr": "-197",
            "underStr": "+147"
          }
        }
      }
    },
    {
      "id": "4f28746c8d3ba89a48ef42722f1bbc9c",
      "home": "New York Mets",
      "away": "Milwaukee Brewers",
      "time": "11:11 PM ET",
      "commence": "2026-08-27T23:11:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "New York Mets +178 / Milwaukee Brewers -194",
        "spread": "New York Mets +1.5 (-104)",
        "total": "O/U 7.0 (Over -115 / Under -105)",
        "raw": {
          "homeML": 178,
          "awayML": -194,
          "homeSpread": 1.5,
          "homeSpreadOdds": -104,
          "awaySpread": -1.5,
          "awaySpreadOdds": -115,
          "total": 7.0,
          "overOdds": -115,
          "underOdds": -105
        }
      },
      "props": {
        "Sean Manaea": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": -165,
            "under": 125,
            "overStr": "-165",
            "underStr": "+125"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 105,
            "under": -145,
            "overStr": "+105",
            "underStr": "-145"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -160,
            "under": 121,
            "overStr": "-160",
            "underStr": "+121"
          }
        },
        "Jacob Misiorowski": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -200,
            "under": 140,
            "overStr": "-200",
            "underStr": "+140"
          },
          "pitcher_strikeouts": {
            "point": 8.5,
            "over": -120,
            "under": -110,
            "overStr": "-120",
            "underStr": "-110"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": 130,
            "under": -175,
            "overStr": "+130",
            "underStr": "-175"
          },
          "pitcher_hits_allowed": {
            "point": 3.5,
            "over": -105,
            "under": -125,
            "overStr": "-105",
            "underStr": "-125"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 113,
            "under": -151,
            "overStr": "+113",
            "underStr": "-151"
          }
        }
      }
    },
    {
      "id": "927a7b09cc5f1512d0324748164c0b5f",
      "home": "Atlanta Braves",
      "away": "Los Angeles Dodgers",
      "time": "11:16 PM ET",
      "commence": "2026-08-27T23:16:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Atlanta Braves -120 / Los Angeles Dodgers +110",
        "spread": "Atlanta Braves -1.5 (+180)",
        "total": "O/U 6.5 (Over -104 / Under -118)",
        "raw": {
          "homeML": -120,
          "awayML": 110,
          "homeSpread": -1.5,
          "homeSpreadOdds": 180,
          "awaySpread": 1.5,
          "awaySpreadOdds": -220,
          "total": 6.5,
          "overOdds": -104,
          "underOdds": -118
        }
      },
      "props": {
        "Yoshinobu Yamamoto": {
          "pitcher_outs": {
            "point": 18.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_strikeouts": {
            "point": 6.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -155,
            "under": 115,
            "overStr": "-155",
            "underStr": "+115"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -105,
            "under": -127,
            "overStr": "-105",
            "underStr": "-127"
          }
        },
        "Chris Sale": {
          "pitcher_outs": {
            "point": 18.5,
            "over": 165,
            "under": -235,
            "overStr": "+165",
            "underStr": "-235"
          },
          "pitcher_strikeouts": {
            "point": 7.5,
            "over": 110,
            "under": -150,
            "overStr": "+110",
            "underStr": "-150"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -130,
            "under": -105,
            "overStr": "-130",
            "underStr": "-105"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 146,
            "under": -196,
            "overStr": "+146",
            "underStr": "-196"
          }
        }
      }
    }
  ]
};

function getGameOdds(homeTeam, awayTeam) {
  return ODDS_DATA.games.find(g =>
    g.home.includes(homeTeam) || g.away.includes(awayTeam)
  ) || null;
}

function getPropLine(gameId, playerName, market) {
  const game = ODDS_DATA.games.find(g => g.id === gameId);
  if (!game) return null;
  const lastName = playerName.split(' ').pop().toLowerCase();
  const playerKey = Object.keys(game.props || {}).find(k =>
    k.toLowerCase().includes(lastName)
  );
  if (!playerKey) return null;
  return game.props[playerKey][market] || null;
}
