// AUTO-GENERATED by odds_fetcher.py — do not edit manually
// Fetched: 2026-08-28T21:41:08.734991+00:00
// Date:    2026-08-28

const ODDS_DATA = {
  "fetched_at": "2026-08-28T21:41:08.734991+00:00",
  "date": "2026-08-28",
  "games": [
    {
      "id": "a6d63d072ba391db5be1a628a064656c",
      "home": "Chicago Cubs",
      "away": "Cincinnati Reds",
      "time": "6:21 PM ET",
      "commence": "2026-08-28T18:21:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Chicago Cubs +7000 / Cincinnati Reds -20000",
        "spread": "Chicago Cubs +1.5 (+1200)",
        "total": "O/U 18.5 (Over +1200 / Under -5000)",
        "raw": {
          "homeML": 7000,
          "awayML": -20000,
          "homeSpread": 1.5,
          "homeSpreadOdds": 1200,
          "awaySpread": -1.5,
          "awaySpreadOdds": -5000,
          "total": 18.5,
          "overOdds": 1200,
          "underOdds": -5000
        }
      },
      "props": {}
    },
    {
      "id": "bb28f14c5f48561498ab3fabd1ebf47b",
      "home": "Detroit Tigers",
      "away": "Los Angeles Dodgers",
      "time": "10:41 PM ET",
      "commence": "2026-08-28T22:41:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Detroit Tigers +162 / Los Angeles Dodgers -174",
        "spread": "Detroit Tigers +1.5 (-118)",
        "total": "O/U 7.5 (Over +102 / Under -124)",
        "raw": {
          "homeML": 162,
          "awayML": -174,
          "homeSpread": 1.5,
          "homeSpreadOdds": -118,
          "awaySpread": -1.5,
          "awaySpreadOdds": -102,
          "total": 7.5,
          "overOdds": 102,
          "underOdds": -124
        }
      },
      "props": {
        "Tarik Skubal": {
          "pitcher_outs": {
            "point": 18.5,
            "over": 120,
            "under": -160,
            "overStr": "+120",
            "underStr": "-160"
          },
          "pitcher_strikeouts": {
            "point": 6.5,
            "over": -165,
            "under": 125,
            "overStr": "-165",
            "underStr": "+125"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -110,
            "under": -125,
            "overStr": "-110",
            "underStr": "-125"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 108,
            "under": -144,
            "overStr": "+108",
            "underStr": "-144"
          }
        },
        "Drew Anderson": {
          "pitcher_outs": {
            "point": 14.5,
            "over": -125,
            "under": -110,
            "overStr": "-125",
            "underStr": "-110"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": 105,
            "under": -145,
            "overStr": "+105",
            "underStr": "-145"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -119,
            "under": -111,
            "overStr": "-119",
            "underStr": "-111"
          }
        }
      }
    },
    {
      "id": "1d34c8ba40aec1ca9cadb1ff7ef37e42",
      "home": "Washington Nationals",
      "away": "Miami Marlins",
      "time": "10:46 PM ET",
      "commence": "2026-08-28T22:46:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Washington Nationals +122 / Miami Marlins -132",
        "spread": "Washington Nationals +1.5 (-150)",
        "total": "O/U 8.5 (Over -104 / Under -118)",
        "raw": {
          "homeML": 122,
          "awayML": -132,
          "homeSpread": 1.5,
          "homeSpreadOdds": -150,
          "awaySpread": -1.5,
          "awaySpreadOdds": 125,
          "total": 8.5,
          "overOdds": -104,
          "underOdds": -118
        }
      },
      "props": {
        "Eury Perez": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -155,
            "under": 115,
            "overStr": "-155",
            "underStr": "+115"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 125,
            "under": -165,
            "overStr": "+125",
            "underStr": "-165"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -120,
            "under": -110,
            "overStr": "-120",
            "underStr": "-110"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -196,
            "under": 147,
            "overStr": "-196",
            "underStr": "+147"
          }
        },
        "Jackson Kent": {
          "pitcher_outs": {
            "point": 14.5,
            "over": -175,
            "under": 125,
            "overStr": "-175",
            "underStr": "+125"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -155,
            "under": 115,
            "overStr": "-155",
            "underStr": "+115"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -195,
            "under": 146,
            "overStr": "-195",
            "underStr": "+146"
          }
        }
      }
    },
    {
      "id": "fab839164ecf4aec65df50e5ee9bbed3",
      "home": "Cleveland Guardians",
      "away": "Kansas City Royals",
      "time": "11:11 PM ET",
      "commence": "2026-08-28T23:11:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Cleveland Guardians -134 / Kansas City Royals +124",
        "spread": "Cleveland Guardians -1.5 (+160)",
        "total": "O/U 7.5 (Over +100 / Under -122)",
        "raw": {
          "homeML": -134,
          "awayML": 124,
          "homeSpread": -1.5,
          "homeSpreadOdds": 160,
          "awaySpread": 1.5,
          "awaySpreadOdds": -194,
          "total": 7.5,
          "overOdds": 100,
          "underOdds": -122
        }
      },
      "props": {
        "Michael Wacha": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -165,
            "under": 125,
            "overStr": "-165",
            "underStr": "+125"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -155,
            "under": 115,
            "overStr": "-155",
            "underStr": "+115"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -115,
            "under": -115,
            "overStr": "-115",
            "underStr": "-115"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -117,
            "under": -113,
            "overStr": "-117",
            "underStr": "-113"
          }
        },
        "Tanner Bibee": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -185,
            "under": 135,
            "overStr": "-185",
            "underStr": "+135"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 110,
            "under": -155,
            "overStr": "+110",
            "underStr": "-155"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -107,
            "under": -124,
            "overStr": "-107",
            "underStr": "-124"
          }
        }
      }
    },
    {
      "id": "233ffa284e1672e4866733dd85fac3e5",
      "home": "New York Mets",
      "away": "Houston Astros",
      "time": "11:11 PM ET",
      "commence": "2026-08-28T23:11:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "New York Mets -104 / Houston Astros -104",
        "spread": "New York Mets +1.5 (-176)",
        "total": "O/U 7.5 (Over -122 / Under +100)",
        "raw": {
          "homeML": -104,
          "awayML": -104,
          "homeSpread": 1.5,
          "homeSpreadOdds": -176,
          "awaySpread": -1.5,
          "awaySpreadOdds": 146,
          "total": 7.5,
          "overOdds": -122,
          "underOdds": 100
        }
      },
      "props": {
        "Hunter Brown": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": 110,
            "under": -150,
            "overStr": "+110",
            "underStr": "-150"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 125,
            "under": -175,
            "overStr": "+125",
            "underStr": "-175"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          },
          "pitcher_walks": {
            "point": 2.5,
            "over": 118,
            "under": -156,
            "overStr": "+118",
            "underStr": "-156"
          }
        },
        "Christian Scott": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": -155,
            "under": 115,
            "overStr": "-155",
            "underStr": "+115"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -165,
            "under": 125,
            "overStr": "-165",
            "underStr": "+125"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 120,
            "under": -160,
            "overStr": "+120",
            "underStr": "-160"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -103,
            "under": -129,
            "overStr": "-103",
            "underStr": "-129"
          }
        }
      }
    },
    {
      "id": "0b16c66db57136bcbe0cb430b3315572",
      "home": "Tampa Bay Rays",
      "away": "San Diego Padres",
      "time": "11:11 PM ET",
      "commence": "2026-08-28T23:11:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Tampa Bay Rays -122 / San Diego Padres +112",
        "spread": "Tampa Bay Rays -1.5 (+172)",
        "total": "O/U 7.5 (Over -102 / Under -120)",
        "raw": {
          "homeML": -122,
          "awayML": 112,
          "homeSpread": -1.5,
          "homeSpreadOdds": 172,
          "awaySpread": 1.5,
          "awaySpreadOdds": -210,
          "total": 7.5,
          "overOdds": -102,
          "underOdds": -120
        }
      },
      "props": {
        "Casey Mize": {
          "pitcher_outs": {
            "point": 15.5,
            "over": 100,
            "under": -140,
            "overStr": "+100",
            "underStr": "-140"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 105,
            "under": -140,
            "overStr": "+105",
            "underStr": "-140"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": 120,
            "under": -160,
            "overStr": "+120",
            "underStr": "-160"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 124,
            "under": -165,
            "overStr": "+124",
            "underStr": "-165"
          }
        },
        "Shane McClanahan": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -200,
            "under": 145,
            "overStr": "-200",
            "underStr": "+145"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -115,
            "under": -118,
            "overStr": "-115",
            "underStr": "-118"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -104,
            "under": -128,
            "overStr": "-104",
            "underStr": "-128"
          }
        }
      }
    },
    {
      "id": "6e66851b93b3cdcc4578b23ae9b93d6d",
      "home": "Atlanta Braves",
      "away": "Colorado Rockies",
      "time": "11:16 PM ET",
      "commence": "2026-08-28T23:16:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Atlanta Braves -220 / Colorado Rockies +200",
        "spread": "Atlanta Braves -1.5 (-106)",
        "total": "O/U 9.0 (Over -110 / Under -110)",
        "raw": {
          "homeML": -220,
          "awayML": 200,
          "homeSpread": -1.5,
          "homeSpreadOdds": -106,
          "awaySpread": 1.5,
          "awaySpreadOdds": -113,
          "total": 9.0,
          "overOdds": -110,
          "underOdds": -110
        }
      },
      "props": {
        "Tomoyuki Sugano": {
          "pitcher_outs": {
            "point": 15.5,
            "over": 125,
            "under": -165,
            "overStr": "+125",
            "underStr": "-165"
          },
          "pitcher_strikeouts": {
            "point": 2.5,
            "over": -175,
            "under": 130,
            "overStr": "-175",
            "underStr": "+130"
          },
          "pitcher_earned_runs": {
            "point": 3.5,
            "over": 105,
            "under": -145,
            "overStr": "+105",
            "underStr": "-145"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -126,
            "under": -105,
            "overStr": "-126",
            "underStr": "-105"
          }
        },
        "Grant Holmes": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -115,
            "under": -118,
            "overStr": "-115",
            "underStr": "-118"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": -140,
            "under": 105,
            "overStr": "-140",
            "underStr": "+105"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -165,
            "under": 125,
            "overStr": "-165",
            "underStr": "+125"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -105,
            "under": -125,
            "overStr": "-105",
            "underStr": "-125"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -112,
            "under": -118,
            "overStr": "-112",
            "underStr": "-118"
          }
        }
      }
    },
    {
      "id": "2458fd8fd2cc9241175e46181d9b3066",
      "home": "New York Yankees",
      "away": "Boston Red Sox",
      "time": "11:16 PM ET",
      "commence": "2026-08-28T23:16:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "New York Yankees -148 / Boston Red Sox +138",
        "spread": "New York Yankees -1.5 (+140)",
        "total": "O/U 7.0 (Over -114 / Under -106)",
        "raw": {
          "homeML": -148,
          "awayML": 138,
          "homeSpread": -1.5,
          "homeSpreadOdds": 140,
          "awaySpread": 1.5,
          "awaySpreadOdds": -170,
          "total": 7.0,
          "overOdds": -114,
          "underOdds": -106
        }
      },
      "props": {
        "Cam Schlittler": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_strikeouts": {
            "point": 6.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -116,
            "under": -115,
            "overStr": "-116",
            "underStr": "-115"
          }
        },
        "Patrick Sandoval": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -140,
            "under": 100,
            "overStr": "-140",
            "underStr": "+100"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -197,
            "under": 147,
            "overStr": "-197",
            "underStr": "+147"
          }
        }
      }
    },
    {
      "id": "365be8fc27b2eb31c003fc150dde54a5",
      "home": "Toronto Blue Jays",
      "away": "Seattle Mariners",
      "time": "11:16 PM ET",
      "commence": "2026-08-28T23:16:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Toronto Blue Jays -138 / Seattle Mariners +128",
        "spread": "Toronto Blue Jays -1.5 (+150)",
        "total": "O/U 7.0 (Over -104 / Under -118)",
        "raw": {
          "homeML": -138,
          "awayML": 128,
          "homeSpread": -1.5,
          "homeSpreadOdds": 150,
          "awaySpread": 1.5,
          "awaySpreadOdds": -182,
          "total": 7.0,
          "overOdds": -104,
          "underOdds": -118
        }
      },
      "props": {
        "Dylan Cease": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -220,
            "under": 160,
            "overStr": "-220",
            "underStr": "+160"
          },
          "pitcher_strikeouts": {
            "point": 7.5,
            "over": 130,
            "under": -175,
            "overStr": "+130",
            "underStr": "-175"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -118,
            "under": -115,
            "overStr": "-118",
            "underStr": "-115"
          },
          "pitcher_hits_allowed": {
            "point": 3.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_walks": {
            "point": 2.5,
            "over": 108,
            "under": -144,
            "overStr": "+108",
            "underStr": "-144"
          }
        },
        "Emerson Hancock": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -130,
            "under": -105,
            "overStr": "-130",
            "underStr": "-105"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": 155,
            "under": -210,
            "overStr": "+155",
            "underStr": "-210"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 110,
            "under": -150,
            "overStr": "+110",
            "underStr": "-150"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -105,
            "under": -125,
            "overStr": "-105",
            "underStr": "-125"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 120,
            "under": -160,
            "overStr": "+120",
            "underStr": "-160"
          }
        }
      }
    },
    {
      "id": "57c478eb2e6623a9a63b654b20634fa1",
      "home": "Milwaukee Brewers",
      "away": "Texas Rangers",
      "time": "11:41 PM ET",
      "commence": "2026-08-28T23:41:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "pitcher_stats": {},
      "lines": {
        "ml": "Milwaukee Brewers -205 / Texas Rangers +186",
        "spread": "Milwaukee Brewers -1.5 (+102)",
        "total": "O/U 7.5 (Over -115 / Under -105)",
        "raw": {
          "homeML": -205,
          "awayML": 186,
          "homeSpread": -1.5,
          "homeSpreadOdds": 102,
          "awaySpread": 1.5,
          "awaySpreadOdds": -122,
          "total": 7.5,
          "overOdds": -115,
          "underOdds": -105
        }
      },
      "props": {
        "Logan Henderson": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_strikeouts": {
            "point": 6.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -145,
            "under": 105,
            "overStr": "-145",
            "underStr": "+105"
          },
          "pitcher_hits_allowed": {
            "point": 3.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 132,
            "under": -176,
            "overStr": "+132",
            "underStr": "-176"
          }
        },
        "Cody Bradford": {
          "pitcher_outs": {
            "point": 15.5,
            "over": 110,
            "under": -150,
            "overStr": "+110",
            "underStr": "-150"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": 165,
            "under": -225,
            "overStr": "+165",
            "underStr": "-225"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -120,
            "under": -110,
            "overStr": "-120",
            "underStr": "-110"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 104,
            "under": -138,
            "overStr": "+104",
            "underStr": "-138"
          }
        }
      }
    }
  ]
};

function getGameOdds(homeTeam, awayTeam) {
  return ODDS_DATA.games.find(g =>
    g.home.includes(homeTeam) || g.away.includes(awayTeam)
  ) || null;
}

function getPropLine(gameId, playerName, market) {
  const game = ODDS_DATA.games.find(g => g.id === gameId);
  if (!game) return null;
  const lastName = playerName.split(' ').pop().toLowerCase();
  const playerKey = Object.keys(game.props || {}).find(k =>
    k.toLowerCase().includes(lastName)
  );
  if (!playerKey) return null;
  return game.props[playerKey][market] || null;
}
