// AUTO-GENERATED by odds_fetcher.py — do not edit manually
// Fetched: 2026-08-25T22:00:23.103211+00:00
// Date:    2026-08-25

const ODDS_DATA = {
  "fetched_at": "2026-08-25T22:00:23.103211+00:00",
  "date": "2026-08-25",
  "games": [
    {
      "id": "209f31db8e00b79cd7185e2e0d10d825",
      "home": "Miami Marlins",
      "away": "Boston Red Sox",
      "time": "10:40 PM ET",
      "commence": "2026-08-25T22:40:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Miami Marlins +131 / Boston Red Sox -140",
        "spread": "Miami Marlins +1.5 (-137)",
        "total": "O/U 7.0 (Over -118 / Under -102)",
        "raw": {
          "homeML": 131,
          "awayML": -140,
          "homeSpread": 1.5,
          "homeSpreadOdds": -137,
          "awaySpread": -1.5,
          "awaySpreadOdds": 114,
          "total": 7.0,
          "overOdds": -118,
          "underOdds": -102
        }
      },
      "props": {
        "Payton Tolle": {
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -105,
            "under": -125,
            "overStr": "-105",
            "underStr": "-125"
          },
          "pitcher_outs": {
            "point": 17.5,
            "over": -165,
            "under": 120,
            "overStr": "-165",
            "underStr": "+120"
          },
          "pitcher_strikeouts": {
            "point": 6.5,
            "over": 105,
            "under": -140,
            "overStr": "+105",
            "underStr": "-140"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 129,
            "under": -172,
            "overStr": "+129",
            "underStr": "-172"
          }
        },
        "Tyler Phillips": {
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -115,
            "under": -115,
            "overStr": "-115",
            "underStr": "-115"
          },
          "pitcher_outs": {
            "point": 14.5,
            "over": -155,
            "under": 115,
            "overStr": "-155",
            "underStr": "+115"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 109,
            "under": -145,
            "overStr": "+109",
            "underStr": "-145"
          }
        }
      }
    },
    {
      "id": "259b6ad0c039c2a2dd00d378d88eb549",
      "home": "Detroit Tigers",
      "away": "Tampa Bay Rays",
      "time": "10:41 PM ET",
      "commence": "2026-08-25T22:41:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Detroit Tigers +116 / Tampa Bay Rays -126",
        "spread": "Detroit Tigers +1.5 (-160)",
        "total": "O/U 7.5 (Over -122 / Under +100)",
        "raw": {
          "homeML": 116,
          "awayML": -126,
          "homeSpread": 1.5,
          "homeSpreadOdds": -160,
          "awaySpread": -1.5,
          "awaySpreadOdds": 130,
          "total": 7.5,
          "overOdds": -122,
          "underOdds": 100
        }
      },
      "props": {
        "Jackson Jobe": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -105,
            "under": -125,
            "overStr": "-105",
            "underStr": "-125"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": 105,
            "under": -145,
            "overStr": "+105",
            "underStr": "-145"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 120,
            "under": -160,
            "overStr": "+120",
            "underStr": "-160"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -140,
            "under": 105,
            "overStr": "-140",
            "underStr": "+105"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -153,
            "under": 115,
            "overStr": "-153",
            "underStr": "+115"
          }
        }
      }
    },
    {
      "id": "4819f8690b221a33563af84c498578c2",
      "home": "Washington Nationals",
      "away": "Colorado Rockies",
      "time": "10:46 PM ET",
      "commence": "2026-08-25T22:46:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Washington Nationals -160 / Colorado Rockies +148",
        "spread": "Washington Nationals -1.5 (+120)",
        "total": "O/U 8.5 (Over -110 / Under -110)",
        "raw": {
          "homeML": -160,
          "awayML": 148,
          "homeSpread": -1.5,
          "homeSpreadOdds": 120,
          "awaySpread": 1.5,
          "awaySpreadOdds": -144,
          "total": 8.5,
          "overOdds": -110,
          "underOdds": -110
        }
      },
      "props": {
        "Andrew Alvarez": {
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 105,
            "under": -140,
            "overStr": "+105",
            "underStr": "-140"
          },
          "pitcher_outs": {
            "point": 15.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -120,
            "under": -111,
            "overStr": "-120",
            "underStr": "-111"
          }
        }
      }
    },
    {
      "id": "187cbd24b1e45a99e9ecaf256baeb7c1",
      "home": "New York Yankees",
      "away": "Houston Astros",
      "time": "11:06 PM ET",
      "commence": "2026-08-25T23:06:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "New York Yankees -138 / Houston Astros +128",
        "spread": "New York Yankees -1.5 (+134)",
        "total": "O/U 8.5 (Over -124 / Under +102)",
        "raw": {
          "homeML": -138,
          "awayML": 128,
          "homeSpread": -1.5,
          "homeSpreadOdds": 134,
          "awaySpread": 1.5,
          "awaySpreadOdds": -162,
          "total": 8.5,
          "overOdds": -124,
          "underOdds": 102
        }
      },
      "props": {
        "Will Warren": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -136,
            "under": 102,
            "overStr": "-136",
            "underStr": "+102"
          }
        },
        "Ethan Pecko": {
          "pitcher_outs": {
            "point": 14.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -115,
            "under": -115,
            "overStr": "-115",
            "underStr": "-115"
          },
          "pitcher_walks": {
            "point": 2.5,
            "over": 130,
            "under": -173,
            "overStr": "+130",
            "underStr": "-173"
          }
        }
      }
    },
    {
      "id": "587e76b251f060a951bfa47ee07cf6ac",
      "home": "Toronto Blue Jays",
      "away": "Kansas City Royals",
      "time": "11:08 PM ET",
      "commence": "2026-08-25T23:08:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Toronto Blue Jays -126 / Kansas City Royals +116",
        "spread": "Toronto Blue Jays -1.5 (+172)",
        "total": "O/U 8.0 (Over -115 / Under -105)",
        "raw": {
          "homeML": -126,
          "awayML": 116,
          "homeSpread": -1.5,
          "homeSpreadOdds": 172,
          "awaySpread": 1.5,
          "awaySpreadOdds": -210,
          "total": 8.0,
          "overOdds": -115,
          "underOdds": -105
        }
      },
      "props": {
        "Max Scherzer": {
          "pitcher_outs": {
            "point": 15.5,
            "over": 125,
            "under": -175,
            "overStr": "+125",
            "underStr": "-175"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 130,
            "under": -185,
            "overStr": "+130",
            "underStr": "-185"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          }
        },
        "Seth Lugo": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -145,
            "under": 105,
            "overStr": "-145",
            "underStr": "+105"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -140,
            "under": 105,
            "overStr": "-140",
            "underStr": "+105"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 103,
            "under": -136,
            "overStr": "+103",
            "underStr": "-136"
          }
        }
      }
    },
    {
      "id": "5adabe1a546de0ad6f64e2789b2b8f8d",
      "home": "New York Mets",
      "away": "Milwaukee Brewers",
      "time": "11:11 PM ET",
      "commence": "2026-08-25T23:11:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "New York Mets +144 / Milwaukee Brewers -156",
        "spread": "New York Mets +1.5 (-130)",
        "total": "O/U 7.5 (Over -105 / Under -115)",
        "raw": {
          "homeML": 144,
          "awayML": -156,
          "homeSpread": 1.5,
          "homeSpreadOdds": -130,
          "awaySpread": -1.5,
          "awaySpreadOdds": 108,
          "total": 7.5,
          "overOdds": -105,
          "underOdds": -115
        }
      },
      "props": {
        "Zach Thornton": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -145,
            "under": 105,
            "overStr": "-145",
            "underStr": "+105"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 110,
            "under": -150,
            "overStr": "+110",
            "underStr": "-150"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -140,
            "under": 105,
            "overStr": "-140",
            "underStr": "+105"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -144,
            "under": 108,
            "overStr": "-144",
            "underStr": "+108"
          }
        },
        "Kyle Harrison": {
          "pitcher_outs": {
            "point": 15.5,
            "over": 110,
            "under": -155,
            "overStr": "+110",
            "underStr": "-155"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": -115,
            "under": -115,
            "overStr": "-115",
            "underStr": "-115"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -130,
            "under": -105,
            "overStr": "-130",
            "underStr": "-105"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 115,
            "under": -154,
            "overStr": "+115",
            "underStr": "-154"
          }
        }
      }
    },
    {
      "id": "d7bed76714eb2b887f979d5156f6863c",
      "home": "Atlanta Braves",
      "away": "Los Angeles Dodgers",
      "time": "11:16 PM ET",
      "commence": "2026-08-25T23:16:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Atlanta Braves +138 / Los Angeles Dodgers -148",
        "spread": "Atlanta Braves +1.5 (-130)",
        "total": "O/U 8.5 (Over -120 / Under -102)",
        "raw": {
          "homeML": 138,
          "awayML": -148,
          "homeSpread": 1.5,
          "homeSpreadOdds": -130,
          "awaySpread": -1.5,
          "awaySpreadOdds": 108,
          "total": 8.5,
          "overOdds": -120,
          "underOdds": -102
        }
      },
      "props": {
        "Bryce Elder": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -145,
            "under": 105,
            "overStr": "-145",
            "underStr": "+105"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -120,
            "under": -110,
            "overStr": "-120",
            "underStr": "-110"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": 105,
            "under": -140,
            "overStr": "+105",
            "underStr": "-140"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -197,
            "under": 147,
            "overStr": "-197",
            "underStr": "+147"
          }
        },
        "Tyler Glasnow": {
          "pitcher_outs": {
            "point": 15.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -130,
            "under": -105,
            "overStr": "-130",
            "underStr": "-105"
          },
          "pitcher_hits_allowed": {
            "point": 3.5,
            "over": -140,
            "under": 105,
            "overStr": "-140",
            "underStr": "+105"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -191,
            "under": 143,
            "overStr": "-191",
            "underStr": "+143"
          }
        }
      }
    },
    {
      "id": "6e7150d8c439882971bcb51d92f290ca",
      "home": "Chicago White Sox",
      "away": "Texas Rangers",
      "time": "11:41 PM ET",
      "commence": "2026-08-25T23:41:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Chicago White Sox +100 / Texas Rangers -110",
        "spread": "Chicago White Sox +1.5 (-184)",
        "total": "O/U 7.5 (Over +102 / Under -124)",
        "raw": {
          "homeML": 100,
          "awayML": -110,
          "homeSpread": 1.5,
          "homeSpreadOdds": -184,
          "awaySpread": -1.5,
          "awaySpreadOdds": 152,
          "total": 7.5,
          "overOdds": 102,
          "underOdds": -124
        }
      },
      "props": {
        "Jacob deGrom": {
          "pitcher_outs": {
            "point": 16.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_strikeouts": {
            "point": 6.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 120,
            "under": -160,
            "overStr": "+120",
            "underStr": "-160"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -133,
            "under": 100,
            "overStr": "-133",
            "underStr": "+100"
          }
        },
        "Anthony Kay": {
          "pitcher_outs": {
            "point": 16.5,
            "over": -115,
            "under": -118,
            "overStr": "-115",
            "underStr": "-118"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": -130,
            "under": -105,
            "overStr": "-130",
            "underStr": "-105"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -165,
            "under": 125,
            "overStr": "-165",
            "underStr": "+125"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -172,
            "under": 129,
            "overStr": "-172",
            "underStr": "+129"
          }
        }
      }
    },
    {
      "id": "928203119cbe56b5e4102e4372ff78bd",
      "home": "St. Louis Cardinals",
      "away": "Baltimore Orioles",
      "time": "11:45 PM ET",
      "commence": "2026-08-25T23:45:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "St. Louis Cardinals -124 / Baltimore Orioles +116",
        "spread": "St. Louis Cardinals -1.5 (+158)",
        "total": "O/U 8.0 (Over -107 / Under -112)",
        "raw": {
          "homeML": -124,
          "awayML": 116,
          "homeSpread": -1.5,
          "homeSpreadOdds": 158,
          "awaySpread": 1.5,
          "awaySpreadOdds": -193,
          "total": 8.0,
          "overOdds": -107,
          "underOdds": -112
        }
      },
      "props": {
        "Matthew Liberatore": {
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -175,
            "under": 125,
            "overStr": "-175",
            "underStr": "+125"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -130,
            "under": -102,
            "overStr": "-130",
            "underStr": "-102"
          },
          "pitcher_outs": {
            "point": 16.5,
            "over": -125,
            "under": -110,
            "overStr": "-125",
            "underStr": "-110"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": -118,
            "under": -108,
            "overStr": "-118",
            "underStr": "-108"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -141,
            "under": 106,
            "overStr": "-141",
            "underStr": "+106"
          }
        },
        "Chris Bassitt": {
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -110,
            "under": -125,
            "overStr": "-110",
            "underStr": "-125"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -105,
            "under": -125,
            "overStr": "-105",
            "underStr": "-125"
          },
          "pitcher_outs": {
            "point": 15.5,
            "over": -130,
            "under": -105,
            "overStr": "-130",
            "underStr": "-105"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -132,
            "under": 104,
            "overStr": "-132",
            "underStr": "+104"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -127,
            "under": -104,
            "overStr": "-127",
            "underStr": "-104"
          }
        }
      }
    },
    {
      "id": "57e5de55a9616dbe31da6693615d0af8",
      "home": "Los Angeles Angels",
      "away": "Cleveland Guardians",
      "time": "1:38 AM ET",
      "commence": "2026-08-26T01:38:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Los Angeles Angels +131 / Cleveland Guardians -140",
        "spread": "Los Angeles Angels +1.5 (-149)",
        "total": "O/U 7.0 (Over -112 / Under -108)",
        "raw": {
          "homeML": 131,
          "awayML": -140,
          "homeSpread": 1.5,
          "homeSpreadOdds": -149,
          "awaySpread": -1.5,
          "awaySpreadOdds": 123,
          "total": 7.0,
          "overOdds": -112,
          "underOdds": -108
        }
      },
      "props": {
        "Gavin Williams": {
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -165,
            "under": 125,
            "overStr": "-165",
            "underStr": "+125"
          },
          "pitcher_outs": {
            "point": 18.5,
            "over": -165,
            "under": 120,
            "overStr": "-165",
            "underStr": "+120"
          },
          "pitcher_strikeouts": {
            "point": 8.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -123,
            "under": -108,
            "overStr": "-123",
            "underStr": "-108"
          }
        },
        "Walbert Urena": {
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_outs": {
            "point": 15.5,
            "over": -118,
            "under": -115,
            "overStr": "-118",
            "underStr": "-115"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": 130,
            "under": -175,
            "overStr": "+130",
            "underStr": "-175"
          },
          "pitcher_walks": {
            "point": 2.5,
            "over": 146,
            "under": -196,
            "overStr": "+146",
            "underStr": "-196"
          }
        }
      }
    },
    {
      "id": "f4592955744665289f90514e92145dcf",
      "home": "Arizona Diamondbacks",
      "away": "Chicago Cubs",
      "time": "1:40 AM ET",
      "commence": "2026-08-26T01:40:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Arizona Diamondbacks +101 / Chicago Cubs -108",
        "spread": "Arizona Diamondbacks +1.5 (-174)",
        "total": "O/U 8.0 (Over -117 / Under -103)",
        "raw": {
          "homeML": 101,
          "awayML": -108,
          "homeSpread": 1.5,
          "homeSpreadOdds": -174,
          "awaySpread": -1.5,
          "awaySpreadOdds": 144,
          "total": 8.0,
          "overOdds": -117,
          "underOdds": -103
        }
      },
      "props": {
        "Clay Holmes": {
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 125,
            "under": -175,
            "overStr": "+125",
            "underStr": "-175"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -140,
            "under": 105,
            "overStr": "-140",
            "underStr": "+105"
          },
          "pitcher_outs": {
            "point": 16.5,
            "over": -105,
            "under": -130,
            "overStr": "-105",
            "underStr": "-130"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -170,
            "under": 128,
            "overStr": "-170",
            "underStr": "+128"
          }
        },
        "Brandon Pfaadt": {
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -120,
            "under": -110,
            "overStr": "-120",
            "underStr": "-110"
          },
          "pitcher_outs": {
            "point": 17.5,
            "over": -135,
            "under": -105,
            "overStr": "-135",
            "underStr": "-105"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": 105,
            "under": -140,
            "overStr": "+105",
            "underStr": "-140"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -127,
            "under": -104,
            "overStr": "-127",
            "underStr": "-104"
          }
        }
      }
    },
    {
      "id": "3c57e2dd92e3e26dff7fb8c2898891bd",
      "home": "Athletics",
      "away": "Minnesota Twins",
      "time": "1:40 AM ET",
      "commence": "2026-08-26T01:40:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Athletics +132 / Minnesota Twins -142",
        "spread": "Athletics +1.5 (-125)",
        "total": "O/U 10.5 (Over -107 / Under -113)",
        "raw": {
          "homeML": 132,
          "awayML": -142,
          "homeSpread": 1.5,
          "homeSpreadOdds": -125,
          "awaySpread": -1.5,
          "awaySpreadOdds": 103,
          "total": 10.5,
          "overOdds": -107,
          "underOdds": -113
        }
      },
      "props": {
        "Taj Bradley": {
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": 105,
            "under": -145,
            "overStr": "+105",
            "underStr": "-145"
          },
          "pitcher_outs": {
            "point": 17.5,
            "over": -145,
            "under": 105,
            "overStr": "-145",
            "underStr": "+105"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": -115,
            "under": -115,
            "overStr": "-115",
            "underStr": "-115"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -192,
            "under": 144,
            "overStr": "-192",
            "underStr": "+144"
          }
        },
        "Gage Jump": {
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_outs": {
            "point": 15.5,
            "over": 105,
            "under": -145,
            "overStr": "+105",
            "underStr": "-145"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": 115,
            "under": -155,
            "overStr": "+115",
            "underStr": "-155"
          },
          "pitcher_walks": {
            "point": 2.5,
            "over": 134,
            "under": -179,
            "overStr": "+134",
            "underStr": "-179"
          }
        }
      }
    },
    {
      "id": "50491a98ba9ab1b1502809e59c3cd776",
      "home": "Seattle Mariners",
      "away": "Philadelphia Phillies",
      "time": "1:40 AM ET",
      "commence": "2026-08-26T01:40:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "Seattle Mariners -104 / Philadelphia Phillies -104",
        "spread": "Seattle Mariners +1.5 (-186)",
        "total": "O/U 8.0 (Over -107 / Under -113)",
        "raw": {
          "homeML": -104,
          "awayML": -104,
          "homeSpread": 1.5,
          "homeSpreadOdds": -186,
          "awaySpread": -1.5,
          "awaySpreadOdds": 153,
          "total": 8.0,
          "overOdds": -107,
          "underOdds": -113
        }
      },
      "props": {
        "George Kirby": {
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 100,
            "under": -135,
            "overStr": "+100",
            "underStr": "-135"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          },
          "pitcher_outs": {
            "point": 17.5,
            "over": -125,
            "under": -110,
            "overStr": "-125",
            "underStr": "-110"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": 140,
            "under": -187,
            "overStr": "+140",
            "underStr": "-187"
          }
        },
        "Aaron Nola": {
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": 100,
            "under": -140,
            "overStr": "+100",
            "underStr": "-140"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": 120,
            "under": -160,
            "overStr": "+120",
            "underStr": "-160"
          },
          "pitcher_outs": {
            "point": 17.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          }
        }
      }
    },
    {
      "id": "ccb7afafeeb739ec9623deb9cba63f64",
      "home": "San Diego Padres",
      "away": "Pittsburgh Pirates",
      "time": "1:40 AM ET",
      "commence": "2026-08-26T01:40:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "San Diego Padres -119 / Pittsburgh Pirates +111",
        "spread": "San Diego Padres -1.5 (+169)",
        "total": "O/U 7.0 (Over -120 / Under +100)",
        "raw": {
          "homeML": -119,
          "awayML": 111,
          "homeSpread": -1.5,
          "homeSpreadOdds": 169,
          "awaySpread": 1.5,
          "awaySpreadOdds": -207,
          "total": 7.0,
          "overOdds": -120,
          "underOdds": 100
        }
      },
      "props": {
        "Paul Skenes": {
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -155,
            "under": 115,
            "overStr": "-155",
            "underStr": "+115"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_outs": {
            "point": 16.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          },
          "pitcher_strikeouts": {
            "point": 6.5,
            "over": 120,
            "under": -160,
            "overStr": "+120",
            "underStr": "-160"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -158,
            "under": 119,
            "overStr": "-158",
            "underStr": "+119"
          }
        },
        "Michael King": {
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": -160,
            "under": 120,
            "overStr": "-160",
            "underStr": "+120"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -120,
            "under": -110,
            "overStr": "-120",
            "underStr": "-110"
          },
          "pitcher_outs": {
            "point": 17.5,
            "over": -148,
            "under": 110,
            "overStr": "-148",
            "underStr": "+110"
          },
          "pitcher_strikeouts": {
            "point": 5.5,
            "over": -105,
            "under": -125,
            "overStr": "-105",
            "underStr": "-125"
          },
          "pitcher_walks": {
            "point": 1.5,
            "over": -191,
            "under": 143,
            "overStr": "-191",
            "underStr": "+143"
          }
        }
      }
    },
    {
      "id": "26d4c80fbedae27b50bb14b2ae483938",
      "home": "San Francisco Giants",
      "away": "Cincinnati Reds",
      "time": "1:46 AM ET",
      "commence": "2026-08-26T01:46:00Z",
      "starters": {
        "away": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "home": {
          "name": "TBD",
          "id": null,
          "hand": "?",
          "confirmed": false
        },
        "source": "MLB Stats API (statsapi.mlb.com)"
      },
      "lines": {
        "ml": "San Francisco Giants -106 / Cincinnati Reds -102",
        "spread": "San Francisco Giants +1.5 (-182)",
        "total": "O/U 7.5 (Over -115 / Under -105)",
        "raw": {
          "homeML": -106,
          "awayML": -102,
          "homeSpread": 1.5,
          "homeSpreadOdds": -182,
          "awaySpread": -1.5,
          "awaySpreadOdds": 150,
          "total": 7.5,
          "overOdds": -115,
          "underOdds": -105
        }
      },
      "props": {
        "Brady Singer": {
          "pitcher_outs": {
            "point": 17.5,
            "over": -135,
            "under": 100,
            "overStr": "-135",
            "underStr": "+100"
          },
          "pitcher_strikeouts": {
            "point": 4.5,
            "over": 105,
            "under": -145,
            "overStr": "+105",
            "underStr": "-145"
          },
          "pitcher_earned_runs": {
            "point": 2.5,
            "over": -110,
            "under": -120,
            "overStr": "-110",
            "underStr": "-120"
          },
          "pitcher_hits_allowed": {
            "point": 5.5,
            "over": -115,
            "under": -115,
            "overStr": "-115",
            "underStr": "-115"
          }
        },
        "Adrian Houser": {
          "pitcher_outs": {
            "point": 15.5,
            "over": 115,
            "under": -160,
            "overStr": "+115",
            "underStr": "-160"
          },
          "pitcher_strikeouts": {
            "point": 3.5,
            "over": -150,
            "under": 110,
            "overStr": "-150",
            "underStr": "+110"
          },
          "pitcher_earned_runs": {
            "point": 1.5,
            "over": 125,
            "under": -165,
            "overStr": "+125",
            "underStr": "-165"
          },
          "pitcher_hits_allowed": {
            "point": 4.5,
            "over": -125,
            "under": -105,
            "overStr": "-125",
            "underStr": "-105"
          }
        }
      }
    },
    {
      "id": "8e42a5450f35bf142633e40243b30561",
      "home": "Detroit Tigers",
      "away": "Tampa Bay Rays",
      "time": "5:11 PM ET",
      "commence": "2026-08-26T17:11:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Detroit Tigers -118 / Tampa Bay Rays +100",
        "spread": "Detroit Tigers +1.5 (-205)",
        "total": "O/U 8.0 (Over -110 / Under -110)",
        "raw": {
          "homeML": -118,
          "awayML": 100,
          "homeSpread": 1.5,
          "homeSpreadOdds": -205,
          "awaySpread": -1.5,
          "awaySpreadOdds": 168,
          "total": 8.0,
          "overOdds": -110,
          "underOdds": -110
        }
      },
      "props": {}
    },
    {
      "id": "191c7378e9557adead7c28fde0673a52",
      "home": "Arizona Diamondbacks",
      "away": "Chicago Cubs",
      "time": "7:41 PM ET",
      "commence": "2026-08-26T19:41:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Arizona Diamondbacks -108 / Chicago Cubs -108",
        "spread": "Arizona Diamondbacks +1.5 (-182)",
        "total": "O/U 8.5 (Over -120 / Under -102)",
        "raw": {
          "homeML": -108,
          "awayML": -108,
          "homeSpread": 1.5,
          "homeSpreadOdds": -182,
          "awaySpread": -1.5,
          "awaySpreadOdds": 150,
          "total": 8.5,
          "overOdds": -120,
          "underOdds": -102
        }
      },
      "props": {}
    },
    {
      "id": "d8f7f270cd38a387ce9133e82dc7b60e",
      "home": "San Francisco Giants",
      "away": "Cincinnati Reds",
      "time": "7:46 PM ET",
      "commence": "2026-08-26T19:46:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "San Francisco Giants -110 / Cincinnati Reds -106",
        "spread": "San Francisco Giants +1.5 (-196)",
        "total": "O/U 7.5 (Over -120 / Under -102)",
        "raw": {
          "homeML": -110,
          "awayML": -106,
          "homeSpread": 1.5,
          "homeSpreadOdds": -196,
          "awaySpread": -1.5,
          "awaySpreadOdds": 162,
          "total": 7.5,
          "overOdds": -120,
          "underOdds": -102
        }
      },
      "props": {}
    },
    {
      "id": "c840ffd21f721ac963c0f3d748f5db02",
      "home": "Los Angeles Angels",
      "away": "Cleveland Guardians",
      "time": "8:08 PM ET",
      "commence": "2026-08-26T20:08:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Los Angeles Angels +116 / Cleveland Guardians -136",
        "spread": "Los Angeles Angels +1.5 (-140)",
        "total": "O/U 9.0 (Over -118 / Under -104)",
        "raw": {
          "homeML": 116,
          "awayML": -136,
          "homeSpread": 1.5,
          "homeSpreadOdds": -140,
          "awaySpread": -1.5,
          "awaySpreadOdds": 116,
          "total": 9.0,
          "overOdds": -118,
          "underOdds": -104
        }
      },
      "props": {}
    },
    {
      "id": "d85bb371f18080847c97ecffd8f5fe93",
      "home": "Seattle Mariners",
      "away": "Philadelphia Phillies",
      "time": "8:11 PM ET",
      "commence": "2026-08-26T20:11:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Seattle Mariners +110 / Philadelphia Phillies -130",
        "spread": "Seattle Mariners +1.5 (-166)",
        "total": "O/U 7.0 (Over -105 / Under -115)",
        "raw": {
          "homeML": 110,
          "awayML": -130,
          "homeSpread": 1.5,
          "homeSpreadOdds": -166,
          "awaySpread": -1.5,
          "awaySpreadOdds": 138,
          "total": 7.0,
          "overOdds": -105,
          "underOdds": -115
        }
      },
      "props": {}
    },
    {
      "id": "baaae4c94f3b7e7c21e2e4219bb5f0fd",
      "home": "San Diego Padres",
      "away": "Pittsburgh Pirates",
      "time": "8:11 PM ET",
      "commence": "2026-08-26T20:11:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "San Diego Padres -126 / Pittsburgh Pirates +108",
        "spread": "San Diego Padres -1.5 (+172)",
        "total": "O/U 8.5 (Over -110 / Under -110)",
        "raw": {
          "homeML": -126,
          "awayML": 108,
          "homeSpread": -1.5,
          "homeSpreadOdds": 172,
          "awaySpread": 1.5,
          "awaySpreadOdds": -210,
          "total": 8.5,
          "overOdds": -110,
          "underOdds": -110
        }
      },
      "props": {}
    },
    {
      "id": "ee171a97363a2c6a55459f804c2d35e6",
      "home": "Miami Marlins",
      "away": "Boston Red Sox",
      "time": "10:41 PM ET",
      "commence": "2026-08-26T22:41:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Miami Marlins +134 / Boston Red Sox -158",
        "spread": "Miami Marlins +1.5 (-130)",
        "total": "O/U 7.5 (Over -120 / Under -102)",
        "raw": {
          "homeML": 134,
          "awayML": -158,
          "homeSpread": 1.5,
          "homeSpreadOdds": -130,
          "awaySpread": -1.5,
          "awaySpreadOdds": 108,
          "total": 7.5,
          "overOdds": -120,
          "underOdds": -102
        }
      },
      "props": {}
    },
    {
      "id": "9fc104e94a575a09146f04bf7bbb0e32",
      "home": "Toronto Blue Jays",
      "away": "Kansas City Royals",
      "time": "11:08 PM ET",
      "commence": "2026-08-26T23:08:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Toronto Blue Jays -132 / Kansas City Royals +112",
        "spread": "Toronto Blue Jays -1.5 (+160)",
        "total": "O/U 8.5 (Over -120 / Under -102)",
        "raw": {
          "homeML": -132,
          "awayML": 112,
          "homeSpread": -1.5,
          "homeSpreadOdds": 160,
          "awaySpread": 1.5,
          "awaySpreadOdds": -194,
          "total": 8.5,
          "overOdds": -120,
          "underOdds": -102
        }
      },
      "props": {}
    },
    {
      "id": "821b22e0957b3177e6e950de4b55696f",
      "home": "New York Mets",
      "away": "Milwaukee Brewers",
      "time": "11:11 PM ET",
      "commence": "2026-08-26T23:11:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "New York Mets +130 / Milwaukee Brewers -154",
        "spread": "New York Mets +1.5 (-134)",
        "total": "O/U 8.0 (Over -120 / Under -102)",
        "raw": {
          "homeML": 130,
          "awayML": -154,
          "homeSpread": 1.5,
          "homeSpreadOdds": -134,
          "awaySpread": -1.5,
          "awaySpreadOdds": 112,
          "total": 8.0,
          "overOdds": -120,
          "underOdds": -102
        }
      },
      "props": {}
    },
    {
      "id": "04da7d827887da84da9926f799c9153d",
      "home": "Atlanta Braves",
      "away": "Los Angeles Dodgers",
      "time": "11:16 PM ET",
      "commence": "2026-08-26T23:16:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Atlanta Braves +110 / Los Angeles Dodgers -130",
        "spread": "Atlanta Braves +1.5 (-160)",
        "total": "O/U 9.0 (Over -102 / Under -120)",
        "raw": {
          "homeML": 110,
          "awayML": -130,
          "homeSpread": 1.5,
          "homeSpreadOdds": -160,
          "awaySpread": -1.5,
          "awaySpreadOdds": 132,
          "total": 9.0,
          "overOdds": -102,
          "underOdds": -120
        }
      },
      "props": {}
    },
    {
      "id": "78fdc67e4f138889d4f1634cb2c5500a",
      "home": "Chicago White Sox",
      "away": "Texas Rangers",
      "time": "11:41 PM ET",
      "commence": "2026-08-26T23:41:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Chicago White Sox -134 / Texas Rangers +114",
        "spread": "Chicago White Sox -1.5 (+160)",
        "total": "O/U 8.0 (Over -110 / Under -110)",
        "raw": {
          "homeML": -134,
          "awayML": 114,
          "homeSpread": -1.5,
          "homeSpreadOdds": 160,
          "awaySpread": 1.5,
          "awaySpreadOdds": -194,
          "total": 8.0,
          "overOdds": -110,
          "underOdds": -110
        }
      },
      "props": {}
    },
    {
      "id": "18cd67572e0e03220737b61b0542a0c0",
      "home": "St. Louis Cardinals",
      "away": "Baltimore Orioles",
      "time": "11:46 PM ET",
      "commence": "2026-08-26T23:46:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "St. Louis Cardinals -108 / Baltimore Orioles -108",
        "spread": "St. Louis Cardinals +1.5 (-188)",
        "total": "O/U 8.0 (Over -115 / Under -105)",
        "raw": {
          "homeML": -108,
          "awayML": -108,
          "homeSpread": 1.5,
          "homeSpreadOdds": -188,
          "awaySpread": -1.5,
          "awaySpreadOdds": 155,
          "total": 8.0,
          "overOdds": -115,
          "underOdds": -105
        }
      },
      "props": {}
    },
    {
      "id": "d8f4d0d32572d2c5acdc10831f7b16b3",
      "home": "Athletics",
      "away": "Minnesota Twins",
      "time": "1:06 AM ET",
      "commence": "2026-08-27T01:06:00Z",
      "starters": {
        "away": {
          "name": "TBD"
        },
        "home": {
          "name": "TBD"
        },
        "source": "pending"
      },
      "lines": {
        "ml": "Athletics +120 / Minnesota Twins -142",
        "spread": "Athletics +1.5 (-130)",
        "total": "O/U 10.0 (Over -105 / Under -115)",
        "raw": {
          "homeML": 120,
          "awayML": -142,
          "homeSpread": 1.5,
          "homeSpreadOdds": -130,
          "awaySpread": -1.5,
          "awaySpreadOdds": 108,
          "total": 10.0,
          "overOdds": -105,
          "underOdds": -115
        }
      },
      "props": {}
    }
  ]
};

function getGameOdds(homeTeam, awayTeam) {
  return ODDS_DATA.games.find(g =>
    g.home.includes(homeTeam) || g.away.includes(awayTeam)
  ) || null;
}

function getPropLine(gameId, playerName, market) {
  const game = ODDS_DATA.games.find(g => g.id === gameId);
  if (!game) return null;
  const lastName = playerName.split(' ').pop().toLowerCase();
  const playerKey = Object.keys(game.props || {}).find(k =>
    k.toLowerCase().includes(lastName)
  );
  if (!playerKey) return null;
  return game.props[playerKey][market] || null;
}
