// SLATE DATA — update daily
// slate_data.js — Oct 05, 2026
// AUTO-GENERATED by slate_builder.py
// Stats source: MLB Stats API (odds_fetcher.py)
// Manual fields: venue, wx, offStats, injuries, xwOBA_vs_opp, batter props

const games = {

  "sox-gua": {
    away:"Chicago White Sox", home:"Cleveland Guardians",
    time:"5:10 PM ET", venue:"TBD",
    awayRec:"TBD", homeRec:"TBD",
    wx:"⛅ Weather TBD",
    starters:"Anthony Kay (?HP) vs Gavin Williams (?HP)",
    overview:{
      lines:{ ml:"Cleveland Guardians -590 / Chicago White Sox +390", spread:"Cleveland Guardians -2.5 (-130)", total:"O/U 8.5 (Over +100 / Under -132)", movement:"" },
      away:{ teamName:"Chicago White Sox", abbr:"SOX",
        offStats:{"avg": ".236", "ops": ".726", "kPct": "24.1", "rPerG": "4.79", "rPerG_L10": "4.79", "rPerG_L5": "4.79"},
        defStats:{"era": "4.44", "bullpenERA_L14": "4.58", "whip": "1.37"},
        starter:{"name": "Anthony Kay", "hand": "?HP", "era": "4.44", "whip": "1.37", "k9": "7.35", "bb9": "3.19", "era_L3": "3.46", "avgIP": "5.1"},
        injuries:[] },
      home:{ teamName:"Cleveland Guardians", abbr:"GUA",
        offStats:{"avg": ".239", "ops": ".696", "kPct": "20.8", "rPerG": "4.19", "rPerG_L10": "4.19", "rPerG_L5": "4.19"},
        defStats:{"era": "3.76", "bullpenERA_L14": "3.46", "whip": "1.11"},
        starter:{"name": "Gavin Williams", "hand": "?HP", "era": "3.76", "whip": "1.11", "k9": "12.11", "bb9": "2.98", "era_L3": "3.52", "avgIP": "5.8"},
        injuries:[] }
    },
    tabs:{
      overview:{intro:"",cards:[]},
      pitcher:{intro:"Props graded Oct 05, 2026",cards:[{"lbl": "Williams — Strikeouts", "pick": "Over 7.5 Ks", "odds": "-140", "grade": "A-", "rat": "Blended K% 34.2% — projects 8.5 Ks vs 7.5 line", "chips": ["Blended K%: 34.2% · proj 8.5 Ks vs 7.5 line", "ERA 3.76 · BB/9 2.98 · avgIP 5.8 · trend NEUTRAL", "L5 ERA: 2.54 · L3 ERA: 3.52"], "src": "MLB Stats API", "pitcherRecency": {"seasonERA": 3.76, "l5ERA": 2.54, "l3ERA": 3.52, "avgIP": 5.8, "bb9": 2.98}}, {"lbl": "Williams — Earned Runs", "pick": "Under 0.5 ER", "odds": "+115", "grade": "B", "rat": "Blended ERA 3.35 — season 3.76 · L5 2.54 · L3 3.52", "chips": ["Blended ERA: 3.35 · 5.8 avg IP", "Season 3.76 · L5 2.54 · L3 3.52", "BB/9 2.98 · park factor 1.0"], "src": "MLB Stats API", "pitcherRecency": {"seasonERA": 3.76, "l5ERA": 2.54, "l3ERA": 3.52, "avgIP": 5.8, "bb9": 2.98}}, {"lbl": "Williams — Outs Recorded", "pick": "Over 15.5 outs", "odds": "+105", "grade": "B", "rat": "Projects 16.7 outs (5.6 IP) vs 15.5 line", "chips": ["Proj 16.7 outs · blended 5.6 avgIP vs 5.2 IP line", "⚠ Trending shorter (L3 avg 5.0 IP vs season 5.8 IP)", "Season avgIP 5.8 · 32 GS · 184 IP"], "src": "MLB Stats API", "pitcherRecency": {"seasonERA": 3.76, "l5ERA": 2.54, "l3ERA": 3.52, "avgIP": 5.8, "bb9": 2.98}}]},
      batter:{intro:"HRR props — lineup position pending",cards:[]}
    }
  },

  "yan-ray": {
    away:"New York Yankees", home:"Tampa Bay Rays",
    time:"8:00 PM ET", venue:"TBD",
    awayRec:"TBD", homeRec:"TBD",
    wx:"⛅ Weather TBD",
    starters:"Cam Schlittler (?HP) vs Freddy Peralta (?HP)",
    overview:{
      lines:{ ml:"Tampa Bay Rays +102 / New York Yankees -120", spread:"Tampa Bay Rays +1.5 (-178)", total:"O/U 6.5 (Over -118 / Under -104)", movement:"" },
      away:{ teamName:"New York Yankees", abbr:"YAN",
        offStats:{"avg": ".235", "ops": ".720", "kPct": "24.7", "rPerG": "4.59", "rPerG_L10": "4.59", "rPerG_L5": "4.59"},
        defStats:{"era": "1.95", "bullpenERA_L14": "3.67", "whip": "0.92"},
        starter:{"name": "Cam Schlittler", "hand": "?HP", "era": "1.95", "whip": "0.92", "k9": "11.11", "bb9": "2.28", "era_L3": "2.0", "avgIP": "5.9"},
        injuries:[] },
      home:{ teamName:"Tampa Bay Rays", abbr:"RAY",
        offStats:{"avg": ".258", "ops": ".728", "kPct": "18.8", "rPerG": "4.54", "rPerG_L10": "4.54", "rPerG_L5": "4.54"},
        defStats:{"era": "4.42", "bullpenERA_L14": "3.81", "whip": "1.33"},
        starter:{"name": "Freddy Peralta", "hand": "?HP", "era": "4.42", "whip": "1.33", "k9": "8.31", "bb9": "3.36", "era_L3": "0.82", "avgIP": "5.3"},
        injuries:[] }
    },
    tabs:{
      overview:{intro:"",cards:[]},
      pitcher:{intro:"Props graded Oct 05, 2026",cards:[{"lbl": "Schlittler — Strikeouts", "pick": "Over 6.5 Ks", "odds": "-125", "grade": "B+", "rat": "Blended K% 31.7% — projects 8.0 Ks vs 6.5 line", "chips": ["Blended K%: 31.7% · proj 8.0 Ks vs 6.5 line", "ERA 1.95 · BB/9 2.28 · avgIP 5.9 · trend NEUTRAL", "L5 ERA: 1.20 · L3 ERA: 2.00"], "src": "MLB Stats API", "pitcherRecency": {"seasonERA": 1.95, "l5ERA": 1.2, "l3ERA": 2.0, "avgIP": 5.9, "bb9": 2.28}}, {"lbl": "Schlittler — Outs Recorded", "pick": "Under 17.5 outs", "odds": "+116", "grade": "A-", "rat": "Projects 17.0 outs (5.7 IP) vs 17.5 line", "chips": ["Proj 17.0 outs · blended 5.7 avgIP vs 5.8 IP line", "⚠ Trending shorter (L3 avg 4.5 IP vs season 5.9 IP)", "Season avgIP 5.9 · 33 GS · 193 IP"], "src": "MLB Stats API", "pitcherRecency": {"seasonERA": 1.95, "l5ERA": 1.2, "l3ERA": 2.0, "avgIP": 5.9, "bb9": 2.28}}, {"lbl": "Peralta — Outs Recorded", "pick": "Over 14.5 outs", "odds": "+108", "grade": "B+", "rat": "Projects 16.3 outs (5.4 IP) vs 14.5 line", "chips": ["Proj 16.3 outs · blended 5.4 avgIP vs 4.8 IP line", "Stable depth (5.3 avgIP · L3 5.5 IP)", "Season avgIP 5.3 · 32 GS · 169 IP"], "src": "MLB Stats API", "pitcherRecency": {"seasonERA": 4.42, "l5ERA": 0.96, "l3ERA": 0.82, "avgIP": 5.3, "bb9": 3.36}}]},
      batter:{intro:"HRR props — lineup position pending",cards:[]}
    }
  }

};

const bestBets = [
  {game:"SOX@GUA", pick:"Over 7.5 Ks", odds:"-140", grade:"A-", src:"MLB Stats API"},
  {game:"YAN@RAY", pick:"Under 17.5 outs", odds:"+116", grade:"A-", src:"MLB Stats API"}
];
